name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run commands on remote server
        run: |
          ssh -o StrictHostKeyChecking=no oswin@home.oswinjerome.in -p 11 << 'EOF'
            cd /home/oswin/Laravel/ikids
            git restore .
            git pull
            npm i
            npm run build:ssr
            composer install
            php artisan migrate
            
          EOF
          
      
